baseURL = 'https://spiderwebrobot.github.io/'
languageCode = 'en-us'
title = 'spiderwebrobot'
theme = 'bitsy'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'github-dark'
    tabWidth = 4
    wrapperClass = 'highlight'
